--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.1.14.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 4/10/2022 8:43:16 AM
-- Server version: 12.0.5000.0
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('1284866157', 110, 2, 2, 'AJU5eHDob/IH7Eemmu7HmbyHcYwZOGDhpEO5DmGm+qW4KxRe37hPBtZSMxv1d+xxYg==', N'مجتبی', N'فرمان آراءبزرگ زاد', N'9218781431')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('1380103622', 104, 2, 2, 'AJvQlBfeXkke1gn1eL3mp4lMO6JkD+WFiLiTTRBo45E1zMBNnMoez38nALIA7E3Ytw==', N'امیر محمد', N'زارع مجتهدی', N'9218781160')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('1465350241', 124, 2, 2, 'AGZar5v4TVnHmLzGLS4eXFbjMgm2ln7sYfr6Y+R5WqS4OvbgweoK4OmiyWxETQFcDA==', N'سعید', N'رحمت نیا', N'9218781371')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('1828279201', 106, 2, 2, 'ACvuNBOmIrmHh/+GMJlMaTDSJC9VTtB7a/OYz2rltuaUIlcIm4/4sNePsOFbr90Okg==', N'هانی', N'ابوعطوی', N'09166008322')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('2050641354', 123, 2, 2, 'AFq5MVy2QzyglG7K3NbkmsLCDSduQ7Kdclffo6hQeoYpSFEpWqbOffINPac9cRv2cg==', N'محمد', N'قلی زاده', N'9128166153')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('2063530971', 102, 2, 2, 'AC03OQzYLN12R8A1seuT3hJEtxbyKj1gJXdhL9RIJDghYQCIBHJGYy1/v4QkcHjJ2Q==', N'محمد باقر', N'جعفر تبار', N'9218783874')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('2753828636', 104, 2, 2, 'AFHf+b/cpRZ3OsWz30o/Slvp31dBF+CFtU7imDcuVgaH5/GzjNOEPaY916eF7ihocg==', N'سعید', N'طالب پور شیشوان', N'9218781307')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('310773814', 131, 2, 1, '1', N'حسن', N'برزگر ماسوله', N'9218780542')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('3255908485', 105, 2, 2, 'AFXEGif4lMyMmzbMuCLHffC9sHEHIEuzQ8YvZdGL+aQE/6VoxbBfrvqxm4i/SVp8wA==', N'مهدی', N'اشرفی', N'9218783343')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('3490175573', 118, 2, 2, 'AHF6868w3/qQvLNcRdx5MYAi/LLslzrHySeNSefVqqIvFgtUMadFBAj1faAR5Ue4zQ==', N'میثم', N'زرین', N'9178568875')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('3732960651', 112, 2, 2, 'ACVrPkmTWtJM2lXzmMyA28OhsU1MBkEgTbCs0yzdz3/OQ3UGGlGB623Tk0mqDSGCqQ==', N'طاها', N'گرامیان', N'9218783148')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('3871606324', 113, 2, 2, 'AEWDrXdAkjrMYqglA5e26btDD+Ltp/MeoPeo851XKxn2OJZluq3u0z9Rrai/on/86A==', N'محمد', N'محمدی شایان', N'9189095695')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4060105872', 115, 2, 2, 'ANwmsu+G7lDH3b4B24UhaYeyO19kfM7ToIPM+9skcB/ic/NXrlCzzRMz32/5ATCIVg==', N'مینا', N'خسروی', N'9218783751')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4230523777', 117, 2, 2, 'AEC8Mq4JQrxrN1JMYYzgeubo8vaOPPcGdnBNA/zKuM/n7H3ZzU1txssp6kyo1QCjJw==', N'نواب', N'ملک حسینی', N'9218783448')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4269932937', 107, 2, 2, 'AJ5XpzEm2t6jp0XTiM5KcA3QRBLGWVY6871Rbqx2EFEJw6xremkJMJurQpCrnkETNg==', N'حامد', N'رضایی', N'9164930388')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4284825968', 119, 2, 2, 'ANSCmRiJS1GZsRgE4W6R6ppjNtKcqNKbkwQYPOTz1jpE3Zke8OsTR1mTkExTpAmNgA==', N'امیرحسین', N'اکبری', N'9218782610')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4322363601', 126, 2, 2, 'ALH3wKQjsyeCbWoIXXhBwD/pQUqQ8/Z2iSdea8185KyTc5nmiNM/Q/r5W/N4VJ1lPg==', N'علی', N'نظری', N'9193855008')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4433658499', 121, 2, 2, 'AGERdBbwtjIax7gj+WmWUgvCrz17KBZpzWJb2Y9oba528h+HB5bTevj1aVwDk/rXFA==', N'حسین', N'عارف منش', N'9218784285')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4500831991', 116, 2, 2, 'AFYdjMn9cwU932ffhrb4fhsgM1StgH+zL/NyYcPEjTFVDdyb1LXICi0Ubqsf0F85WQ==', N'امیر', N'بلوچی', N'9218781645')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('450249905', 100, 2, 2, 'AP0Nq5WdvLZbcO0EdRn92JnTCPUoaJX9C75wWQYEjX0C5DQqYMUKJrUvU7ldS0lSkg==', N'مازیار', N'فراهانی', N'9218783980')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4591205053', 111, 2, 2, 'AFPvPteSLHR2lwd8p/mi2hFDPUm45PLTcPuo88UL6mMqZguptBHPBo60mDBpo6UfAQ==', N'مهدی', N'سعیدی', N'9359450654')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('4621788949', 114, 2, 2, 'ACYEIu2mR9hFlKnJepPvBOYNcXCdOPCCCus/uQl6157BhzaHsghVllfax5SJJ+BIFg==', N'محمد', N'رضوی', N'9190236861')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('5230025956', 108, 2, 2, 'AIZYbsiUKlMtwhTwQBCBhvmmSvWOq/5DuUxf7Cy5vrsqsHTojF0xMA2k/89oOiSnsQ==', N'احسان', N'یعقوبی', N'09131409914')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('58737782', 131, 2, 2, 'AGPPbGNNBoftY2yFe7T8s9wPwPZBtoan8wNqSpCgUqNv/6kBcNzM66EPBcjjAE1JyQ==', N'حسین', N'کشوری', N'9218780551')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('60592893', 131, 2, 1, 'AEnkVAtFbfSyq8//ugVOLqGG7aDwtV9CVgr+PnGfuQ32qFJE82htpw5eeItGMQ5gDg==', N'رضا', N'اسلامی نیا', N'9378019833')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('651921449', 129, 2, 2, 'AGNfOmaVXirMYyqbai93DJZOY1IUpi63cQq5FES6Du8ya3CmpoRmuCGZ8b03fEpLrQ==', N'محمدرضا', N'شبانی', N'9218782032')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('6539894661', 101, 2, 2, 'AKbZGzvVgxLmOGzJWkXxXsh1j8Q5gxN5tnGd5ttXUMioo8v+KCDku4CqBZLGzUyLSQ==', N'مرتضی', N'نوری', N'9218783015')
INSERT expdata(Id, ProvinceId, LOVDepartmentId, UserLevelId, Password, Name, Family, PhoneNumber) VALUES ('941199762', 109, 2, 2, 'AKuTtBzFB9euHzrmtUIMqbaNIN9rR8vn2QGU7m1iDlAV7KK/y/lE2BEPo66yTtPCFA==', N'یاسر', N'صادقی', N'9218782130')
GO